[images.minio]
repository = "harbor.riwi.dev/minio/minio"
tag = "RELEASE.2024-07-16T23-46-41Z"

[images.garage]
repository = "dxflrs/garage"
tag = "v2.4.1"

[images.seaweedfs]
repository = "chrislusf/seaweedfs"
tag = "4.47"

[images.rustfs]
repository = "rustfs/rustfs"
tag = "1.0.0"
